/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './angular-payments.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
class AngularPaymentsModuleInjector extends import0.ɵNgModuleInjector<import1.AngularPaymentsModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ReactiveFormsModule_3:import3.ReactiveFormsModule;
  _AngularPaymentsModule_4:import1.AngularPaymentsModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __ɵi_6:import3.ɵi;
  __FormBuilder_7:import3.FormBuilder;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  get _FormBuilder_7():import3.FormBuilder {
    if ((this.__FormBuilder_7 == null)) { (this.__FormBuilder_7 = new import3.FormBuilder()); }
    return this.__FormBuilder_7;
  }
  createInternal():import1.AngularPaymentsModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ReactiveFormsModule_3 = new import3.ReactiveFormsModule();
    this._AngularPaymentsModule_4 = new import1.AngularPaymentsModule();
    return this._AngularPaymentsModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import1.AngularPaymentsModule)) { return this._AngularPaymentsModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AngularPaymentsModuleNgFactory:import0.NgModuleFactory<import1.AngularPaymentsModule> = new import0.NgModuleFactory<any>(AngularPaymentsModuleInjector,import1.AngularPaymentsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzL1Byb2plY3RzL2FuZ3VsYXItcGF5bWVudHMtdHMvc3JjL2FuZ3VsYXItcGF5bWVudHMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2NocmlzL1Byb2plY3RzL2FuZ3VsYXItcGF5bWVudHMtdHMvc3JjL2FuZ3VsYXItcGF5bWVudHMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
